version: 2
jobs:
  build:
    working_directory: ~/store-retreive
    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - restore_cache:
          key: store-retreive-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: store-retreive-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/store-retreive-0.0.1-SNAPSHOT
      - run: mvn test
  deploy:
      machine:
          enabled: true
      working_directory: ~/store-retreive
      environment:
        HEROKU_APP: "sleepy-refuge-55486"
      steps:
        - checkout
        - run:
            name: Setup Heroku
            command: bash .circleci/setup-heroku.sh
        - run:
            command: |
              git push heroku sequential-branch-filter:master
              heroku run rake db:migrate
              sleep 5  # sleep for 5 seconds to wait for dynos
              heroku restart
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master